name: Todo Item
description: Create a todo to help keep track.
title: "[TODO]: "
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Todo
      description: >-
        A clear and concise description of what to do.
